package net.thumbtack.school.ttschool;

public enum TrainingErrorCode {
    TRAINEE_WRONG_FIRSTNAME,
    TRAINEE_WRONG_LASTNAME,
    TRAINEE_WRONG_RATING,
    TRAINEE_NOT_FOUND,
    DUPLICATE_TRAINEE,

    GROUP_WRONG_NAME,
    GROUP_WRONG_ROOM,
    GROUP_NOT_FOUND,

    SCHOOL_WRONG_NAME,
    DUPLICATE_GROUP_NAME,

    EMPTY_TRAINEE_QUEUE
}
